imports:
    - { resource: parameters.yml }

github:
  authentication:
    token_or_login: '%github_authentication_token_or_login%'
    password_or_secret: '%github_authentication_password_or_secret%'
    method: '%github_authentication_method%'
